# Generated by Django 2.2 on 2020-04-09 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_question_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_list',
            field=models.ManyToManyField(blank=True, related_name='question_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
