# Generated by Django 2.2 on 2020-04-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200409_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnQuestionList',
        ),
    ]
