# Generated by Django 2.2 on 2020-04-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200410_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='question_list',
            new_name='questions',
        ),
    ]
