# Generated by Django 2.2 on 2020-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
