# Generated by Django 2.2 on 2020-04-09 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='user_history',
            field=models.ManyToManyField(related_name='npc_history', through='game.User_NPC', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='world',
            name='user_history',
            field=models.ManyToManyField(related_name='world_history', through='game.User_World', to=settings.AUTH_USER_MODEL),
        ),
    ]
